name: Discord 3DS Build

on: workflow_dispatch, push

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Discord3DS:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build
      - name: Discord 3DS Build
        run: PLATFORM=3DS make   